"""change fields starttime and endtime from datetime to time in availability

Revision ID: e2fcdf7a4288
Revises: 0e5db40dc7c7
Create Date: 2026-02-08 15:06:42.787413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2fcdf7a4288'
down_revision: Union[str, Sequence[str], None] = '0e5db40dc7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
